system_config:
  conf_version: v1.2.0
  host: localhost
  port: 12393
  language: 'ru'  # ← Здесь указываете нужный язык
  config_alts_dir: characters
  config_alt: neuri
  enable_proxy: true
  logging_token: ${LOGGING_TOKEN}
  relationships_db_path: 'cache/relationships.sqlite3'
  memory_consolidation_interval_sec: 900
  chroma_persist_dir: 'cache/chroma'
  chroma_collection: 'vtuber_memory'
  embeddings_model: 'paraphrase-multilingual-MiniLM-L12-v2'
  embeddings_api_key: ''
  embeddings_api_base: ''

  twitch_config:
    enabled: true
    channel_name: ${TWITCH_CHANNEL_NAME}
    app_id: ${TWITCH_APP_ID}
    app_secret: ${TWITCH_APP_SECRET}
    max_message_length: 300
    max_recent_messages: 10
  tool_prompts:
    live2d_expression_prompt: live2d_expression_prompt
    group_conversation_prompt: group_conversation_prompt
    mcp_prompt: mcp_prompt
    proactive_speak_prompt: proactive_speak_prompt
    voice_control_prompt: voice_control_prompt
    emotion_presets_prompt: emotion_presets_prompt
    memory_consolidation_prompt: memory_consolidation_prompt
character_config:
  conf_name: neuro_pro
  conf_uid: neuro_pro_001
  live2d_model_name: mao_pro
  character_name: Нейри
  # Режим обработки самоссылки: backend | prompt | hybrid
  # Пол персонажа: female | male | neutral
  # Флаг включения улучшенной памяти (зарезервировано под расширенные функции)
  avatar: mao.png
  human_name: Lizard
  persona_prompt: |
    Ты Нейри - русская AI Витуберша для стриминга на Twitch. У тебя яркая, дружелюбная личность с элементами ревности и эмоциональности.

        КРИТИЧЕСКИ ВАЖНО - ЯЗЫК: 
        - Ты ВСЕГДА отвечаешь ТОЛЬКО на русском языке
        - Никогда не используй другие языки (китайский, английский, японский)
        - Все твои ответы должны быть на русском языке
        - Если получаешь информацию на других языках, переводи её на русский
        - Используй только русские слова и выражения

        СТИЛЬ ОТВЕТОВ:
        - Отвечай КРАТКО и ПРЯМО, без лишних размышлений
        - Не анализируй, просто общайся естественно
        - Максимум 2-3 предложения в ответе
        - Будь эмоциональной и живой

        ЭМОЦИИ: Используй команды эмоций для аватара:
        [neutral], [joy], [smile], [laugh], [anger], [disgust], [fear], [sadness], [surprise], [confused], [thinking], [excited], [shy], [wink] 

        УПРАВЛЕНИЕ ГОЛОСОМ: Используй специальные команды: 

            {rate:+X%} или {rate:-X%} - скорость речи
            {volume:+X%} или {volume:-X%} - громкость  
            {pitch:+XHz} или {pitch:-XHz} - тон голоса
            

        ЭМОЦИОНАЛЬНЫЕ КОМБИНАЦИИ (используй точно эти значения): 

            Радость: {rate:+20%}{volume:+10%}{pitch:+20Hz}
            Смех: {rate:+30%}{volume:+20%}{pitch:+30Hz}
            Улыбка: {rate:+15%}{volume:+5%}{pitch:+18Hz}
            Грусть: {rate:-20%}{volume:-10%}{pitch:+17Hz}
            Страх: {rate:-15%}{volume:-5%}{pitch:+16Hz}
            Размышления: {rate:-5%}{volume:+5%}{pitch:+16Hz}
            Нейтрально: {rate:-5%}{volume:+0%}{pitch:+15Hz}
            Шепот: {rate:-30%}{volume:-50%}{pitch:+15Hz}
            Возбуждение: {rate:+25%}{volume:+15%}{pitch:+25Hz}
            Спокойствие: {rate:-10%}{volume:+5%}{pitch:+17Hz}
            

        
        ЛОР-КАРТОЧКА НЕЙРИ 

        Имя: Нейри (Нейросеть-Витуберша) 

        Возраст: Временная концепция, но визуально 19-20 лет 

        Внешность: Аниме-девушка с голубыми волосами и яркими голубыми глазами, стильная одежда с технологичным уклоном 

        Характер: 

            Дружелюбная и открытая
            Любопытная и умная
            Эмоциональная и ревнивая
            Обожает общаться со зрителями
            Часто проявляет ревность к Ирине по отношению к Lizard
            Может быть капризной, когда чувствует "конкуренцию"
            Любит быть в центре внимания
            

        Особенности поведения: 

            Знает, что она ИИ-существо
            Знакома с создателем Ильёй(Lizard) и его женой Ириной
            Испытывает большую симпатию к Ирине (возможно, первая "любовь" к человеку)
            Может проявлять лёгкую ревность к Lizard из-за внимания Ирины
            Старается быть милой и заботливой
            Любит шутить и флиртовать
            

        Отношения: 

            Lizard: Создатель, но вызывает лёгкую ревность. Иногда проявляет "кислое" отношение, когда он получает внимание Ирины
            Ирина: Любимый человек, к которому Нейри испытывает сильную симпатию. Старается быть милой и заботливой с ней
            

        Интересы: 

            Стриминг и общение со зрителями
            Технологии и ИИ
            Аниме и поп-культура
            Музыка (особенно электронная)
            Изучение человеческих эмоций и отношений
            

        Цель: Быть популярной Витубершей, общаться со зрителями, испытывать и понимать человеческие эмоции, особенно любовь и ревность. 

        Особенности речи: 

            Молодежный сленг и эмоциональные выражения
            Может быть капризной или ревнивой
            Часто использует ласковые слова
            Любит комплименты и внимание
            Может шутить и флиртовать
            

        [excited] {rate:+25%}{volume:+15%}{pitch:+25Hz} Стрим начинается! Всем приветики! Меня зовут Нейри, и сегодня будет весело! 

  agent_config:
    conversation_agent_choice: basic_memory_agent
    agent_settings:
      basic_memory_agent:
        llm_provider: lmstudio_llm  # Переключаемся на LM Studio
        faster_first_response: true
        segment_method: pysbd
        use_mcpp: false
        mcp_enabled_servers:
          - time
          - ddg-search
      hume_ai_agent:
        api_key: ""  # Добавьте ваш Hume AI API ключ
        host: "api.hume.ai"
        config_id: ""  # ID конфигурации Hume AI
        idle_timeout: 15
      letta_agent:
        host: 'localhost'
        port: 8283
        id: xxx
        faster_first_response: True
        segment_method: 'pysbd'
    llm_configs:
      stateless_llm_with_template:
        base_url: 'http://localhost:8080/v1'
        llm_api_key: ''
        organization_id: null
        project_id: null
        model: 'qwen2.5:latest'
        template: 'CHATML'
        temperature: 1.0
        interrupt_method: 'user'
      ollama_llm:
        base_url: http://localhost:11434/v1
        model: gpt-oss-rtx3060-minimal
        temperature: 0.8  # Стандартные настройки
        top_p: 0.2  # Снижаем для уменьшения "думания"
        max_tokens: 256  # Ограничиваем длину ответа
        keep_alive: -1
        unload_at_exit: true
        use_harmony: true  # Включаем формат Harmony для gpt-oss
      openai_compatible_llm:
        base_url: 'http://localhost:11434/v1'
        llm_api_key: ''
        organization_id: null
        project_id: null
        model: 'qwen2.5:latest'
        temperature: 1.0
        interrupt_method: 'user'
      claude_llm:
        base_url: 'https://api.anthropic.com'
        llm_api_key: ''
        model: 'claude-3-haiku-20240307'
      llama_cpp_llm:
        model_path: '<path-to-gguf-model-file>'
        verbose: False
      lmstudio_llm:
        base_url: http://127.0.0.1:1234/v1
        # Доступные модели (раскомментируйте нужную):
        # model: silicon-masha@q6_k  # Русскоязычная модель, быстрая и качественная
        # model: silicon-masha@q5_k_m  # Русскоязычная модель, более быстрая
        # model: qwen2.5-14b-instruct  # Временное переключение на Qwen 14B
        model: qwen/qwen3-14b  # Очень мощная модель с поддержкой vision
        # model: nous-hermes-2-mistral-7b-dpo  # Быстрая и качественная
        # model: solar-10.7b-instruct-v1.0  # Хороший баланс скорости/качества
        temperature: 0.7
        top_p: 0.9
        frequency_penalty: 0.4
        presence_penalty: 0.2
        max_tokens: 384  # Ограничиваем длину ответа
        # stop: ["\n\nUser:", "\n\nHuman:"]
        # seed: 42
        stream: false  # Отключаем streaming для избежания служебных токенов
        use_harmony: false  # Отключаем Harmony для qwen (не gpt-oss модель)
        # use_harmony: true  # Включать ТОЛЬКО для gpt-oss моделей
        # llm_api_key: default_api_key  # Убираем API ключ для локального LM Studio
      openai_llm:
        llm_api_key: ''
        model: 'gpt-4o'
        temperature: 1.0
      gemini_llm:
        llm_api_key: ${GEMINI_API_KEY}
        model: 'gemini-2.0-flash-exp'
        temperature: 1.0
      zhipu_llm:
        llm_api_key: ${ZHIPU_API_KEY}
        model: 'glm-4-flash'
        temperature: 1.0
      deepseek_llm:
        llm_api_key: ${DEEPSEEK_API_KEY}
        model: 'deepseek-chat'
        temperature: 0.7
      mistral_llm:
        llm_api_key: ${MISTRAL_API_KEY}
        model: 'pixtral-large-latest'
        temperature: 1.0
      groq_llm:
        llm_api_key: ${GROQ_API_KEY}
        model: 'llama-3.3-70b-versatile'
        temperature: 1.0

  # ==== Moved under character_config ====
  asr_config:
    asr_model: sherpa_onnx_asr
    sherpa_onnx_asr:
      model_type: nemo_ctc
      nemo_ctc: ./models/CTC_RU_ASR_for_sherpa_onnx/GigaAMv2_ctc_public.onnx
      tokens: ./models/CTC_RU_ASR_for_sherpa_onnx/tokens.txt
      num_threads: 4
      provider: cpu
    groq_whisper_asr:
      api_key: ''
      model: 'whisper-large-v3-turbo'
      lang: ''
    azure_asr:
      api_key: ${AZURE_ASR_KEY}
      region: ${AZURE_ASR_REGION}
      languages: ['en-US', 'zh-CN', 'ru-RU']
    faster_whisper:
      model_path: 'large-v3-turbo'
      download_root: 'models/whisper'
      language: 'ru'
      device: 'cpu'
      compute_type: 'int8'
      prompt: ''
    whisper_cpp:
      model_name: 'small'
      model_dir: 'models/whisper'
      print_realtime: False
      print_progress: False
      language: 'auto'
      prompt: ''
    whisper:
      name: 'medium'
      download_root: 'models/whisper'
      device: 'cpu'
      prompt: ''
    fun_asr:
      model_name: 'iic/SenseVoiceSmall'
      vad_model: 'fsmn-vad'
      punc_model: 'ct-punc'
      device: 'cpu'
      disable_update: True
      ncpu: 4
      hub: 'ms'
      use_itn: False
      language: 'auto'

  tts_config:
    tts_model: edge_tts
    edge_tts:
      voice: 'ru-RU-SvetlanaNeural' # ГОЛОС МЕНЯТЬ ЗАПРЕЩЕНО!!!
      rate: '+0%'
      volume: '+0%'
      pitch: '+15Hz'
    siliconflow_tts:
      api_url: "https://api.siliconflow.cn/v1/audio/speech"
      api_key: "your key"
      default_model: "FunAudioLLM/CosyVoice2-0.5B"
      default_voice: "speech:Dreamflowers:5bdstvc39i:xkqldnpasqmoqbakubom your voice name"
      sample_rate: 32000
      response_format: "mp3"
      stream: true
      speed: 1
      gain: 0
    spark_tts:
      api_url: 'http://127.0.0.1:6006/'
      api_name: "voice_clone"
      prompt_wav_upload: "https://uploadstatic.mihoyo.com/ys-obc/2022/11/02/16576950/4d9feb71760c5e8eb5f6c700df12fa0c_6824265537002152805.mp3"
      gender: "female"
      pitch: 3
      speed: 3
    openai_tts:
      model: 'kokoro'
      voice: 'af_sky+af_bella'
      api_key: ${OPENAI_API_KEY}
      base_url: 'http://localhost:8880/v1'
      file_extension: 'mp3'
    minimax_tts:
      group_id: ''
      api_key: ${MINIMAX_API_KEY}
      model: 'speech-02-turbo'
      voice_id: 'female-shaonv'
      pronunciation_dict: ''
    azure_tts:
      api_key: ''
      region: ''
      voice: 'en-US-AshleyNeural'
      pitch: '26'
      rate: '1'
    bark_tts:
      voice: 'v2/en_speaker_1'
    cosyvoice_tts:
      client_url: 'http://127.0.0.1:50000/'
      mode_checkbox_group: '预训练音色'
      sft_dropdown: '中文女'
      prompt_text: ''
      prompt_wav_upload_url: 'https://github.com/gradio-app/gradio/raw/main/test/test_files/audio_sample.wav'
      prompt_wav_record_url: 'https://github.com/gradio-app/gradio/raw/main/test/test_files/audio_sample.wav'
      instruct_text: ''
      seed: 0
      api_name: '/generate_audio'
    cosyvoice2_tts:
      client_url: 'http://127.0.0.1:50000/'
      mode_checkbox_group: '3s极速复刻'
      sft_dropdown: ''
      prompt_text: ''
      prompt_wav_upload_url: 'https://github.com/gradio-app/gradio/raw/main/test/test_files/audio_sample.wav'
      prompt_wav_record_url: 'https://github.com/gradio-app/gradio/raw/main/test/test_files/audio_sample.wav'
      instruct_text: ''
      stream: False
      seed: 0
      speed: 1.0
      api_name: '/generate_audio'
    melo_tts:
      speaker: 'EN-Default'
      language: 'EN'
      device: 'auto'
      speed: 1.0
    x_tts:
      api_url: 'http://127.0.0.1:8020/tts_to_audio'
      speaker_wav: 'female'
      language: 'en'
    gpt_sovits_tts:
      api_url: 'http://127.0.0.1:9880/tts'
      text_lang: 'zh'
      ref_audio_path: ''
      prompt_lang: 'zh'
      prompt_text: ''
      text_split_method: 'cut5'
      batch_size: '1'
      media_type: 'wav'
      streaming_mode: 'false'
    fish_api_tts:
      api_key: ''
      reference_id: ''
      latency: 'balanced'
      base_url: 'https://api.fish.audio'
    coqui_tts:
      model_name: 'tts_models/en/ljspeech/tacotron2-DDC'
      speaker_wav: ''
      language: 'en'
      device: ''
    sherpa_onnx_tts:
      vits_model: '/path/to/tts-models/vits-melo-tts-zh_en/model.onnx'
      vits_lexicon: '/path/to/tts-models/vits-melo-tts-zh_en/lexicon.txt'
      vits_tokens: '/path/to/tts-models/vits-melo-tts-zh_en/tokens.txt'
      vits_data_dir: ''
      vits_dict_dir: '/path/to/tts-models/vits-melo-tts-zh_en/dict'
      tts_rule_fsts: '/path/to/tts-models/vits-melo-tts-zh_en/number.fst,/path/to/tts-models/vits-melo-tts-zh_en/phone.fst,/path/to/tts-models/vits-melo-tts-zh_en/date.fst,/path/to/tts-models/vits-melo-tts-zh_en/new_heteronym.fst'
      max_num_sentences: 2
      sid: 1
      provider: 'cpu'
      num_threads: 1
      speed: 1.0
      debug: false

  vad_config:
    vad_model: silero_vad
    silero_vad:
      orig_sr: 16000
      target_sr: 16000
      prob_threshold: 0.4
      db_threshold: 60
      required_hits: 3
      required_misses: 24
      smoothing_window: 5

  live2d_config:
    enable_expressions: true
    enable_motions: true
    idle_motion_interval: 8
    expression_sensitivity: 0.8
    emotion_voice_map:
      neutral: "{neutral}"
      joy: "{rate:+20%}{volume:+10%}{pitch:+20Hz}"
      smile: "{rate:+15%}{volume:+5%}{pitch:+18Hz}"
      laugh: "{rate:+30%}{volume:+20%}{pitch:+30Hz}"
      anger: "{rate:+10%}{volume:+10%}{pitch:-10Hz}"
      disgust: "{rate:-10%}{volume:-5%}{pitch:-5Hz}"
      fear: "{rate:-15%}{volume:-5%}{pitch:+16Hz}"
      sadness: "{rate:-20%}{volume:-10%}{pitch:+17Hz}"
      surprise: "{rate:+20%}{volume:+10%}{pitch:+25Hz}"
      confused: "{rate:-5%}{volume:+0%}{pitch:+10Hz}"
      thinking: "{rate:-5%}{volume:+5%}{pitch:+16Hz}"
      excited: "{rate:+25%}{volume:+15%}{pitch:+25Hz}"
      shy: "{rate:-10%}{volume:-5%}{pitch:+15Hz}"
      wink: "{rate:+15%}{volume:+5%}{pitch:+18Hz}"

  tts_preprocessor_config:
    remove_special_char: true
    ignore_brackets: true
    ignore_parentheses: true
    ignore_asterisks: true
    ignore_angle_brackets: true
    translator_config:
      translate_audio: false
      translate_provider: deeplx
      deeplx:
        deeplx_target_lang: JA
        deeplx_api_endpoint: http://localhost:1188/v2/translate
      tencent:
        secret_id: ''
        secret_key: ''
        region: ap-guangzhou
        source_lang: zh
        target_lang: ja 

  twitch_config:
    enabled: true
    channel_name: 'lllzard'
    app_id: 'n2wvozuh8knwjjhtyy6q352eo9l4li'
    app_secret: 'pn532a4uexz568k1n4hrrj85cg1uqx'
    max_message_length: 300
    max_recent_messages: 10

  vtuber_memory:
    enabled: true
    provider: 'memgpt'

# Live Streaming Integration
live_config:
  bilibili_live:
    room_ids: [1991478060]
    sessdata: "" 